### ISSUE TITLE
Python2 dependency issue, Python3 not available

### ISSUE THREAD

**Issue by AlexisTM** [ammsa/Githeat#5]
Hi,

This happens on clean installation:

Python2 is not installable due to GitPython asking for Python 3.4 when installing with Python 2.7 (=> downgrade GitPython version or fix its version?)

```bash
$ pip install githeat
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Collecting githeat
  Downloading githeat-0.1.2-py2-none-any.whl (21 kB)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from githeat) (1.14.0)
Requirement already satisfied: smmap in /usr/local/lib/python2.7/dist-packages/smmap-3.0.1-py2.7.egg (from githeat) (3.0.1)
Requirement already satisfied: PyYAML in ./.local/lib/python2.7/site-packages (from githeat) (3.13)
Requirement already satisfied: python-dateutil in /usr/local/lib/python2.7/dist-packages (from githeat) (2.8.1)
Collecting xtermcolor
  Downloading xtermcolor-1.3.tar.gz (3.8 kB)
Requirement already satisfied: py in /usr/lib/python2.7/dist-packages (from githeat) (1.5.2)
Requirement already satisfied: wheel in /usr/lib/python2.7/dist-packages (from githeat) (0.30.0)
Requirement already satisfied: GitPython in /usr/local/lib/python2.7/dist-packages/GitPython-3.1.0-py2.7.egg (from githeat) (3.1.0)
ERROR: Package 'GitPython' requires a different Python: 2.7.17 not in '>=3.4'
WARNING: You are using pip version 20.1.1; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/bin/python2 -m pip install --upgrade pip' command.
```

Python3 is simply not available.

```bash
$ pip3 install githeat
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement githeat (from versions: none)
ERROR: No matching distribution found for githeat
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
```

One way to fix it is to change requirements to the last Python2 compatible version for these two packages:

```bash
pip install gitpython==2.1.15
pip install gitdb==0.6.4
```

**Comment by ammsa** [comment]
be19afd fixes this. `pip3 install githeat` should work now. Give it a try?

**Comment by AlexisTM** [comment]
It now installs with Python3.

For some reason, my PyYaml version was not upgraded from 3.13 to 5.1 as in requirements.txt, upgrading it `pip3 install pyyaml -U` (to version 5.3.1) makes githeat work

```
Traceback (most recent call last):
  File "/home/alexis/.local/bin/githeat", line 5, in <module>
    from githeat import main
  File "/home/alexis/.local/lib/python3.6/site-packages/githeat/__init__.py", line 7, in <module>
    from .__main__ import main
  File "/home/alexis/.local/lib/python3.6/site-packages/githeat/__main__.py", line 21, in <module>
    from .core import config
  File "/home/alexis/.local/lib/python3.6/site-packages/githeat/core/__init__.py", line 7, in <module>
    from ._config import *
  File "/home/alexis/.local/lib/python3.6/site-packages/githeat/core/_config.py", line 11, in <module>
    from yaml import FullLoader
ImportError: cannot import name 'FullLoader'
```

**Comment by AlexisTM** [comment]
I will close this because it should be fixed and would have worked if I hadn't pyyaml already installed.
